data_root: data

data_file:
    root_dir: data/data_file
    source_URL: https://github.com/GautamaShastry/Datasets/raw/main/housing-data.zip
    local_data_file: data/data_file/data.zip
    unzip_dir: data/data_file


data_validation:
    root_dir: data/data_validation
    unzip_data_dir: data/data_file/housing.csv
    STATUS_FILE: data/data_validation/status.txt


data_transformation:
    root_dir: data/data_transformation
    data_path: data/data_file/housing.csv


model_trainer:
    root_dir: data/model_trainer
    train_data_path: data/data_transformation/train.csv
    test_data_path: data/data_transformation/test.csv
    model_name: model.joblib

