artifacts_root: artifacts

data ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/GautamaShastry/Branching-tutorial/raw/master/
    local_data_file: artifacts/data_ingestion/
    unzip_dir: artifacts/data_ingestion

